server:
  port: 9002

spring:
  application:
    name: nacos-dubbo-user-consumer
  cloud:
    sentinel:
      web-context-unify: false # 关闭 context 整合
      filter:
        enabled: false
      transport:
        port: 8719
        dashboard: 192.168.209.133:8858
dubbo:
  registry:
    address: nacos://192.168.209.133:8848

service:
  version: 1.0.0


